const mongoose=require('mongoose')
const RastuarantSchema=new mongoose.Schema({
    title:{
        type:String,
        required:true,
    },
    time:{
        type:String,
        required:true,
    },
    imageUrl:{
        type:String,
        required:true,
    },
    foods:{
        type:Array,
        required:false,
        default:[]
    },
    pickup:{
        type:Boolean,
        default:false,
    },
    delivery:{
        type:Boolean,
        default:false,
    },
    isAvailable:{
        type:Boolean,
        default:false,
    },
    owner:{
        type:String,
        required:true,
    },
    code:{
        type:String,
        required:true,
    },
    logoUrl:{
        type:String,
        required:true,
    },
    rating:{
        type:Number,
        required:true,
        min:0,
        max:5,
        default:3
    },
    ratingCount:{
        type:String,
        default:"267"
    },
    verification:{
        type:String,
        required:false,
        default:"Pending",
        enum:["Pending","Verified","Rejected"]
    },
    verificationMessage:{
        type:String,
        default:"Your Restuarant is under review. We will notify you once it is verified",
        required:true,
    },
    coordinates:{
        id:{type:String},
        latitude:{type:Number,required:true},
        longitude:{type:Number,required:true},
        latitudeDelta:{type:Number,default:0.0122},
        longitudeDelta:{type:Number,default:0.0122},
        address:{type:String,required:true},
        title:{type:String,required:true},
    }
});
module.exports=mongoose.model('Rastuarant',RastuarantSchema);